const flags = ["100% working", "18+"];

const gamesList = [
    //18+
    { id: "tgse26gsd-btbr", title: "Beat Banger", img: "random/btbr.jpg", category: "", params: "|random/btbr/index", tags: ["18+"], plays: 0 },

    //Organized by folder
    { id: "tgse26gsd-tozofret", title: "2048", img: "tozofret.jpg", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-cedoge", title: "Chrome Dino Game", img: "cedoge.jpg", category: "", tags: ["100% working"], plays: 0 },

    //Random
    { id: "tgse26gsd-bkstre", title: "Buckshot Roulette", img: "random/bkstre.jpg", params: "|random/bkstre/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-bntk", title: "Bergentruck 201X", img: "random/bntk.jpg", params: "|random/bntk/BERGENTRUCK_201X", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-ueyw", title: "Undertale Yellow", img: "random/ueyw.jpg", params: "|random/ueyw/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-wbfg", title: "Web Fishing", img: "random/wbfg.jpg", params: "|random/wbfg/index", category: "", tags: ["100% working"], plays: 0 },

    //Unity WebGL
    { id: "tgse26gsd-crpt", title: "Clover Pit", img: "unitywgl/crpt.jpg", params: "?game=unitywgl/crpt|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-gyto", title: "Granny 2", img: "unitywgl/gyto.jpg", params: "?game=unitywgl/gyto|.1system/unity/indexold", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-fgga", title: "Flying Gorilla", img: "unitywgl/fgga.jpg", params: "?game=unitywgl/fgga|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-inlg", title: "Iron Lung", img: "unitywgl/inlg.jpg", params: "?game=unitywgl/inlg|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-udgege", title: "Untitled Goose Game", img: "unitywgl/udgege.jpg", params: "?game=unitywgl/udgege|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-aatear", title: "Amanda The Adventurer", img: "unitywgl/aatear.jpg", params: "?game=unitywgl/aatear|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-fh", title: "Fish", img: "unitywgl/fh.jpg", params: "?game=unitywgl/fh|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-fstofm", title: "Fears To Fathom: Home Alone", img: "unitywgl/fstofm.jpg", params: "?game=unitywgl/fstofm|.1system/unity/indexold", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-ggorit", title: "Getting Over It", img: "unitywgl/ggorit.jpg", params: "?game=unitywgl/ggorit|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-mkmnkn", title: "Milkman Karlson", img: "unitywgl/mkmnkn.jpg", params: "?game=unitywgl/mkmnkn|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pepygd", title: "People Playground", img: "unitywgl/pepygd.jpg", params: "?game=unitywgl/pepygd|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-rt", title: "Raft", img: "unitywgl/rt.jpg", params: "?game=unitywgl/rt|.1system/unity/indexold", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-sdss", title: "Speed Starts", img: "unitywgl/sdss.jpg", params: "?game=unitywgl/sdss|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-slbyrnay", title: "Schoolboy Runaway", img: "unitywgl/slbyrnay.jpg", params: "?game=unitywgl/slbyrnay|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-statmdnt", title: "Shift At Midnight", img: "unitywgl/statmdnt.jpg", params: "?game=unitywgl/statmdnt|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-temninteww", title: "The Man In The Window", img: "unitywgl/temninteww.jpg", params: "?game=unitywgl/temninteww|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-tetl", title: "Tattle Tail", img: "unitywgl/tetl.jpg", params: "?game=unitywgl/tetl|.1system/unity/indexold", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-uakl", title: "Ultrakill", img: "unitywgl/uakl.jpg", params: "?game=unitywgl/uakl|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },

    //Unorganized
    { id: "tgse26gsd-awee", title: "Arrow Escape", img: "awee.jpg", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-mectpe061aa", title: "Minecraft PE v0.6.1 alpha", img: "mect/mectpe061aa.jpg", category: "", params: "|mect/mectpe061aa/index", tags: [], plays: 0 },
    
    //Flash Ruffle
    { id: "tgse26gsd-pasbaa", title: "Papa's Bakeria", img: "pasga/pasbaa.jpg", params: "?game=pasga/pasbaa|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pasbua", title: "Papa's Burgeria", img: "pasga/pasbua.jpg", params: "?game=pasga/pasbua|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pascha", title: "Papa's Cheeseria", img: "pasga/pascha.jpg", params: "?game=pasga/pascha|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pascua", title: "Papa's Cupcakeria", img: "pasga/pascua.jpg", params: "?game=pasga/pascua|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pasda", title: "Papa's Donuteria", img: "pasga/pasda.jpg", params: "?game=pasga/pasda|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pasfa", title: "Papa's Freezeria", img: "pasga/pasfa.jpg", params: "?game=pasga/pasfa|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pasha", title: "Papa's Hotdoggeria", img: "pasga/pasha.jpg", params: "?game=pasga/pasha|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-paspana", title: "Papa's Pancakeria", img: "pasga/paspana.jpg", params: "?game=pasga/paspana|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-paspasa", title: "Papa's Pastaria", img: "pasga/paspasa.jpg", params: "?game=pasga/paspasa|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-paspiza", title: "Papa's Pizzeria", img: "pasga/paspiza.jpg", params: "?game=pasga/paspiza|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-passca", title: "Papa's Scooperia", img: "pasga/passca.jpg", params: "?game=pasga/passca|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-passua", title: "Papa's Sushiria", img: "pasga/passua.jpg", params: "?game=pasga/passua|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-paswa", title: "Papa's Wingeria", img: "pasga/paswa.jpg", params: "?game=pasga/paswa|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pastoma", title: "Papa's Taco Mia!", img: "pasga/pastoma.jpg", params: "?game=pasga/pastoma|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pasma", title: "Papa's Mocharia", img: "pasga/pasma.jpg", params: "?game=pasga/pasma|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-vxoe", title: "Vex", img: "vx/vxoe.jpg", params: "?game=vx/vxoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-vxto", title: "Vex 2", img: "vx/vxto.jpg", params: "?game=vx/vxto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-vxte", title: "Vex 3", img: "vx/vxte.jpg", params: "?game=vx/vxte|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-teieqzoe", title: "The Impossible Quiz", img: "teieqz/teieqzoe.jpg", params: "?game=teieqz/teieqzoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-teieqzto", title: "The Impossible Quiz 2", img: "teieqz/teieqzto.jpg", params: "?game=teieqz/teieqzto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-resloe", title: "Riddle School", img: "resl/resloe.jpg", params: "?game=resl/resloe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-reslto", title: "Riddle School 2", img: "resl/reslto.jpg", params: "?game=resl/reslto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-reslte", title: "Riddle School 3", img: "resl/reslte.jpg", params: "?game=resl/reslte|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-reslfr", title: "Riddle School 4", img: "resl/reslfr.jpg", params: "?game=resl/reslfr|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-reslfe", title: "Riddle School 5", img: "resl/reslfe.jpg", params: "?game=resl/reslfe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-hooe", title: "Hobo", img: "hobo/hooe.jpg", params: "?game=hobo/hooe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-hoto", title: "Hobo 2: Prison Brawl", img: "hobo/hoto.jpg", params: "?game=hobo/hoto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-hote", title: "Hobo 3: Wanted", img: "hobo/hote.jpg", params: "?game=hobo/hote|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-hofr", title: "Hobo 4: Total War", img: "hobo/hofr.jpg", params: "?game=hobo/hofr|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-hofe", title: "Hobo 5: Space Brawls", img: "hobo/hofe.jpg", params: "?game=hobo/hofe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-hosx", title: "Hobo 6: Hell", img: "hobo/hosx.jpg", params: "?game=hobo/hosx|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-hosn", title: "Hobo 7: Heaven", img: "hobo/hosn.jpg", params: "?game=hobo/hosn|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-fybsoe", title: "Factory Balls", img: "fybs/fybsoe.jpg", params: "?game=fybs/fybsoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-fybsto", title: "Factory Balls 2", img: "fybs/fybsto.jpg", params: "?game=fybs/fybsto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-fybste", title: "Factory Balls 3", img: "fybs/fybste.jpg", params: "?game=fybs/fybste|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-fybsfr", title: "Factory Balls 4", img: "fybs/fybsfr.jpg", params: "?game=fybs/fybsfr|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-entodeoe", title: "Earn To Die", img: "entode/entodeoe.jpg", params: "?game=entode/entodeoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-entodeto", title: "Earn To Die 2", img: "entode/entodeto.jpg", params: "?game=entode/entodeto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-dkleoe", title: "Duck Life", img: "dkle/dkleoe.jpg", params: "?game=dkle/dkleoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-dkleto", title: "Duck Life 2", img: "dkle/dkleto.jpg", params: "?game=dkle/dkleto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-dklete", title: "Duck Life 3", img: "dkle/dklete.jpg", params: "?game=dkle/dklete|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-dklefr", title: "Duck Life 4", img: "dkle/dklefr.jpg", params: "?game=dkle/dklefr|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pcoe", title: "Pandemic", img: "pc/pcoe.jpg", params: "?game=pc/pcoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-pcto", title: "Pandemic 2", img: "pc/pcto.jpg", params: "?game=pc/pcto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-rtwsoe", title: "Raft Wars", img: "rtws/rtwsoe.jpg", params: "?game=rtws/rtwsoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-rtwsto", title: "Raft Wars 2", img: "rtws/rtwsto.jpg", params: "?game=rtws/rtwsto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-skwr", title: "Stick War", img: "orfh/skwr.jpg", params: "?game=orfh/skwr|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-hyws", title: "Happy Wheels", img: "orfh/hyws.jpg", params: "?game=orfh/hyws|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-tewshtgeto", title: "The Worlds Hardest Game 2", img: "orfh/tewshtgeto.jpg", params: "?game=orfh/tewshtgeto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-rdblte", title: "Red Ball 3", img: "rdbl/rdblte.jpg", params: "?game=rdbl/rdblte|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-rdblfr", title: "Red Ball 4", img: "rdbl/rdblfr.jpg", params: "?game=rdbl/rdblfr|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-rdblfe", title: "Red Ball 5", img: "rdbl/rdblfe.jpg", params: "?game=rdbl/rdblfe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-srsroe", title: "Sugar, Sugar", img: "srsr/srsroe.jpg", params: "?game=srsr/srsroe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-srsrto", title: "Sugar, Sugar 2", img: "srsr/srsrto.jpg", params: "?game=srsr/srsrto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-srsrte", title: "Sugar, Sugar 3", img: "srsr/srsrte.jpg", params: "?game=srsr/srsrte|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-tecmoe", title: "The Classroom", img: "tecm/tecmoe.jpg", params: "?game=tecm/tecmoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-tecmto", title: "The Classroom 2", img: "tecm/tecmto.jpg", params: "?game=tecm/tecmto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-tecmte", title: "The Classroom 3", img: "tecm/tecmte.jpg", params: "?game=tecm/tecmte|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-retroe", title: "Riddle Transfer", img: "retr/retroe.jpg", params: "?game=retr/retroe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-retrto", title: "Riddle Transfer 2", img: "retr/retrto.jpg", params: "?game=retr/retrto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-iroe", title: "Infectionator", img: "ir/iroe.jpg", params: "?game=ir/iroe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-irto", title: "Infectionator 2", img: "ir/irto.jpg", params: "?game=ir/irto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-aeofwroe", title: "Age Of War", img: "aeofwr/aeofwroe.jpg", params: "?game=aeofwr/aeofwroe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-aeofwrto", title: "Age Of War 2", img: "aeofwr/aeofwrto.jpg", params: "?game=aeofwr/aeofwrto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-aeofwrte", title: "Age Of War 3", img: "aeofwr/aeofwrte.jpg", params: "?game=aeofwr/aeofwrte|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-lntofyoe", title: "Learn To Fly", img: "lntofy/lntofyoe.jpg", params: "?game=lntofy/lntofyoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-lntofyto", title: "Learn To Fly 2", img: "lntofy/lntofyto.jpg", params: "?game=lntofy/lntofyto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-lntofyte", title: "Learn To Fly 3", img: "lntofy/lntofyte.jpg", params: "?game=lntofy/lntofyte|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-lntofyie", title: "Learn To Fly Idle", img: "lntofy/lntofyie.jpg", params: "?game=lntofy/lntofyie|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-sefehsoe", title: "Strike Force Heroes", img: "sefehs/sefehsoe.jpg", params: "?game=sefehs/sefehsoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-sefehsto", title: "Strike Force Heroes 2", img: "sefehs/sefehsto.jpg", params: "?game=sefehs/sefehsto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-sefehste", title: "Strike Force Heroes 3", img: "sefehs/sefehste.jpg", params: "?game=sefehs/sefehste|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-bstrdeoe", title: "Bloons Tower Defense", img: "bstrde/bstrdeoe.jpg", params: "?game=bstrde/bstrdeoe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-bstrdeto", title: "Bloons Tower Defense 2", img: "bstrde/bstrdeto.jpg", params: "?game=bstrde/bstrdeto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-bstrdete", title: "Bloons Tower Defense 3", img: "bstrde/bstrdete.jpg", params: "?game=bstrde/bstrdete|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-bstrdefr", title: "Bloons Tower Defense 4", img: "bstrde/bstrdefr.jpg", params: "?game=bstrde/bstrdefr|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-bstrdefe", title: "Bloons Tower Defense 5", img: "bstrde/bstrdefe.jpg", params: "?game=bstrde/bstrdefe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    { id: "tgse26gsd-dbwstode", title: "Dumb Ways To Die", img: "orfh/dbwstode.jpg", params: "?game=orfh/dbwstode|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },

    //{ id: "tgse26gsd-demd", title: "Drive Mad", img: "demd.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-robl", title: "Retro Bowl", img: "robl.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-gyst", title: "Getaway Shootout", img: "gyst.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-rpss", title: "Rooftop Snipers", img: "rpss.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-tlrh", title: "Tunnel Rush", img: "tlrh.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-crrh", title: "Cluster Rush", img: "crrh.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-slpe", title: "Slope", img: "se/slpe.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-prioto", title: "Paper.io 2", img: "prio/prioto.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-moxmwr", title: "Moto X3M Winter", img: "moxm/moxmwr.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-moxmsyld", title: "Moto X3M Spooky Land", img: "moxm/moxmsyld.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-prio", title: "Paper.io", img: "prio/prio.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-oooe", title: "OvO", img: "oo/oooe.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-ooto", title: "OvO 2", img: "oo/ooto.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-oods", title: "OvO Dimensions", img: "oo/oods.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-oevoell", title: "1v1.LOL", img: "lol/oevoell.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-gydh", title: "Geometry Dash", img: "shcy/gydh.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-syssbg", title: "Subway Surfers Beijing", img: "syss/syssbg.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-cecr", title: "Cookie Clicker", img: "cecr.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-btrm", title: "Basket Random", img: "btrm/btrm.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-bgrm", title: "Boxing Random", img: "btrm/bgrm.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-srrm", title: "Soccer Random", img: "btrm/srrm.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-vyrm", title: "Volley Random", img: "btrm/vyrm.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-myhs", title: "Muddy Heights", img: "unitywgl/myhs.jpg", params: "?game=unitywgl/myhs|.1system/unity/indexold", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-sytsoe", title: "Slendy Tubbies", img: "unitywgl/sytsoe.jpg", params: "?game=unitywgl/sytsoe|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-wsyrdy", title: "Whos Your Daddy", img: "unitywgl/wsyrdy.jpg", params: "?game=unitywgl/wsyrdy|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-mise", title: "MiSide", img: "unitywgl/mise.jpg", category: "", params: "?game=unitywgl/mise|.1system/unity/index", tags: ["18+"], plays: 0 },
    //{ id: "tgse26gsd-sers", title: "Slime Ranchers", img: "unitywgl/sers.jpg", params: "?game=unitywgl/sers|.1system/unity/indexold", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-sytsto", title: "Slendy Tubbies 2", img: "unitywgl/sytsto.jpg", params: "?game=unitywgl/sytsto|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-gatg", title: "Gorilla Tag", img: "unitywgl/gatg.jpg", params: "?game=unitywgl/gatg|.1system/unity/index", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-rdbloe", title: "Red Ball", img: "rdbl/rdbloe.jpg", params: "?game=rdbl/rdbloe|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-rdblto", title: "Red Ball 2", img: "rdbl/rdblto.jpg", params: "?game=rdbl/rdblto|.1system/ruffle", category: "", tags: ["100% working"], plays: 0 },
    //{ id: "tgse26gsd-vxte", title: "Vex 3", img: "vx/vxte.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-vxfr", title: "Vex 4", img: "vx/vxfr.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-vxfe", title: "Vex 5", img: "vx/vxfe.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-pcsr", title: "Pandemic Simulator", img: "pcsr.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-pgttmm", title: "Parking Ticket Mayhem", img: "pgttmm.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-segs", title: "Stumble Guys", img: "segs.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-tlio", title: "Territorial.io", img: "tlio.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-vxsx", title: "Vex 6", img: "vx/vxsx.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-vxsn", title: "Vex 7", img: "vx/vxsn.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-vxet", title: "Vex 8", img: "vx/vxet.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-seto", title: "Slope 2", img: "seto.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-rnte", title: "Run 3", img: "rnte.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-mnstcsto", title: "Madalin Stunt Cars 2", img: "mnstcs/mnstcsto.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-mncsmr", title: "Madalin Cars Multiplayer", img: "mnstcs/mncsmr.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-shks", title: "Smash Karts", img: "shks.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-blss", title: "Basketball Stars", img: "blss.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-fyadwl", title: "Fireboy and Watergirl", img: "fyadwl.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-moxm", title: "Moto X3M", img: "moxm/moxm.jpg", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-paspala", title: "Papa's Paleteria", img: "pasga/paspala.jpg", params: "?game=paspala|.1system/ruffle", category: "", tags: [], plays: 0 },
    //{ id: "tgse26gsd-pascla", title: "Papa's Cluckeria", img: "pasga/pascla.jpg", params: "?game=pascla|.1system/ruffle", category: "", tags: [], plays: 0 },
];